from __future__ import annotations

FEATURES = [
{'id': 'F1', 'name': '自然语言意图输入', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F2', 'name': '意图DSL编译', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F3', 'name': '策略自动规划', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F4', 'name': '策略冲突检测', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F5', 'name': '路径可达性验证', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F6', 'name': 'SLA可行性预测', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F7', 'name': '配置自动下发', 'status': 'simulation', 'mode': 'API + UI + CLI', 'external_dependency': True},
{'id': 'F8', 'name': '配置原子回滚', 'status': 'simulation', 'mode': 'API + UI + CLI', 'external_dependency': True},
{'id': 'F9', 'name': '实时遥测采集', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F10', 'name': '遥测数据推送', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F11', 'name': '异常自动检测', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F12', 'name': '故障自动诊断', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F13', 'name': '自动自愈执行', 'status': 'simulation', 'mode': 'API + UI + CLI', 'external_dependency': True},
{'id': 'F14', 'name': '自愈报告生成', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F15', 'name': 'Agent间A2A任务传递', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F16', 'name': '跨域Agent协商', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F17', 'name': 'Agent执行可视化', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F18', 'name': 'LangGraph条件分支兼容接口', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F19', 'name': '人工审批节点', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F20', 'name': '工具MCP标准化', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F21', 'name': '自定义大模型', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F22', 'name': '分Agent绑定模型', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F23', 'name': '模型连接测试', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F24', 'name': '离线自动降级', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F25', 'name': '自定义规则', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F26', 'name': '规则实时验证', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F27', 'name': '自定义工具', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F28', 'name': '自定义工作流', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F29', 'name': '工作流实时生效', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F30', 'name': '自定义Agent', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F31', 'name': '自定义主题', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F32', 'name': '自定义字体', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F33', 'name': '配置导入导出', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F34', 'name': '外部MCP服务器接入', 'status': 'simulation', 'mode': 'API + UI + CLI', 'external_dependency': True},
{'id': 'F35', 'name': '网络拓扑动态展示', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F36', 'name': 'SLA与指标仪表盘', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F37', 'name': '事件流时间线', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F38', 'name': '拓扑节点下钻', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F39', 'name': '意图输入控制台', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F40', 'name': '意图模板管理', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F41', 'name': 'Agent协作图', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F42', 'name': 'Agent节点下钻', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F43', 'name': '策略冲突报告', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F44', 'name': '遥测监控曲线', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F45', 'name': '自愈事件时间线', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F46', 'name': '手动故障注入', 'status': 'simulation', 'mode': 'API + UI + CLI', 'external_dependency': True},
{'id': 'F47', 'name': '实时推送更新', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F48', 'name': 'Docker Compose一键部署', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F49', 'name': '预置演示拓扑', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F50', 'name': '仿真/真实双驱动', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F51', 'name': '跨平台支持', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F52', 'name': '自动化基准测试', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F53', 'name': '网络操作日志', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F54', 'name': 'Agent执行日志', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F55', 'name': '日志筛选与搜索', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F56', 'name': '实时日志流', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F57', 'name': '意图执行历史', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F58', 'name': '自愈事件历史', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F59', 'name': '执行回放', 'status': 'implemented', 'mode': 'API + UI + CLI', 'external_dependency': False},
{'id': 'F60', 'name': '对话Agent', 'status': 'implemented', 'mode': 'API + config', 'external_dependency': False},
{'id': 'F61', 'name': 'SSH物理网络驱动', 'status': 'simulation', 'mode': 'API + config', 'external_dependency': True},
{'id': 'F62', 'name': '设备凭据管理', 'status': 'implemented', 'mode': 'API + config', 'external_dependency': False},
{'id': 'F63', 'name': 'Markdown报告生成', 'status': 'implemented', 'mode': 'API + config', 'external_dependency': False},
{'id': 'F64', 'name': '报告模板定制', 'status': 'implemented', 'mode': 'API + config', 'external_dependency': False},
{'id': 'F65', 'name': '工具调用序列图', 'status': 'implemented', 'mode': 'API + config', 'external_dependency': False},
{'id': 'F66', 'name': '危险命令拦截与确认', 'status': 'implemented', 'mode': 'API + config', 'external_dependency': False}
]

def feature_matrix():
    return {
        "total": len(FEATURES),
        "implemented_entrypoints": len([f for f in FEATURES if f["status"] in {"implemented", "simulation"}]),
        "production_ready": len([f for f in FEATURES if f["status"] == "implemented" and not f.get("external_dependency")]),
        "simulation_safe": len([f for f in FEATURES if f["status"] == "simulation"]),
        "external_dependency": len([f for f in FEATURES if f.get("external_dependency")]),
        "items": FEATURES,
    }
